name: reto


services:
  frontend:
    build:
      context: ./reto-frontend
      dockerfile: Dockerfile
    container_name: frontend
    # ports:
    #   - '3000:3000'
    # volumes:
      #- ./reto-frontend:/app
      #- /app/node_modules
    networks:
      - frontend-net
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "20080:80"
      - "20443:443"
    networks:
      - frontend-net
      - backend-net
      - database-net
    depends_on:
      - frontend
      

networks:
  frontend-net:
  backend-net:
  database-net: