import datetime
import json
import os
import random
import uuid

from faker import Faker
from websocket import create_connection

from providers.generator import Generator

fake = Faker()


class GithubProvider(Generator):
    def __init__(self, config):
        super().__init__(config)

    def generate(self):
        type = random.choices(["push", "pull_request.opened", "pull_request.closed"],
                              weights=[0.6, 0.25, 0.15], k=1)
        if type[0] == "push":
            print("Generating github push event")
            ws_github = create_connection(f"ws://{self.config["WS_HOST"]}/events/ingestion/github/ws",
                                          header={
                                              "Accept": "*/*",
                                              "Content-Type": "application/json",
                                              "User-Agent": "GitHub-Hookshot/300dae6",
                                              "X-GitHub-Delivery": str(uuid.uuid4()),
                                              "X-GitHub-Event": "push",
                                              "X-GitHub-Hook-ID": "474170556",
                                              "X-GitHub-Hook-Installation-Target-ID": "167820875",
                                              "X-GitHub-Hook-Installation-Target-Type": "organization"
                                          })
            commits = [generate_github_commit() for _ in range(1, 12)]
            body = {
                "ref": "refs/heads/develop",
                "before": "0cc1a68aeeb011721adbfc92faecfb6d481bc284",
                "after": "40e200b007313b55c2d82fbf713a02d7be19a8d7",
                "repository": {
                    "id": 790463501,
                    "node_id": "R_kgDOLx2EDQ",
                    "name": "Reto",
                    "full_name": "RetoBancolombia/Reto",
                    "private": True,
                    "owner": {
                        "name": "RetoBancolombia",
                        "email": None,
                        "login": "RetoBancolombia",
                        "id": 167820875,
                        "node_id": "O_kgDOCgC-Sw",
                        "avatar_url": "https://avatars.githubusercontent.com/u/167820875?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/RetoBancolombia",
                        "html_url": "https://github.com/RetoBancolombia",
                        "followers_url": "https://api.github.com/users/RetoBancolombia/followers",
                        "following_url": "https://api.github.com/users/RetoBancolombia/following{/other_user}",
                        "gists_url": "https://api.github.com/users/RetoBancolombia/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/RetoBancolombia/subscriptions",
                        "organizations_url": "https://api.github.com/users/RetoBancolombia/orgs",
                        "repos_url": "https://api.github.com/users/RetoBancolombia/repos",
                        "events_url": "https://api.github.com/users/RetoBancolombia/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/RetoBancolombia/received_events",
                        "type": "Organization",
                        "site_admin": False
                    },
                    "html_url": "https://github.com/RetoBancolombia/Reto",
                    "description": None,
                    "fork": False,
                    "url": "https://github.com/RetoBancolombia/Reto",
                    "forks_url": "https://api.github.com/repos/RetoBancolombia/Reto/forks",
                    "keys_url": "https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/RetoBancolombia/Reto/teams",
                    "hooks_url": "https://api.github.com/repos/RetoBancolombia/Reto/hooks",
                    "issue_events_url": "https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/RetoBancolombia/Reto/events",
                    "assignees_url": "https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/RetoBancolombia/Reto/tags",
                    "blobs_url": "https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/RetoBancolombia/Reto/languages",
                    "stargazers_url": "https://api.github.com/repos/RetoBancolombia/Reto/stargazers",
                    "contributors_url": "https://api.github.com/repos/RetoBancolombia/Reto/contributors",
                    "subscribers_url": "https://api.github.com/repos/RetoBancolombia/Reto/subscribers",
                    "subscription_url": "https://api.github.com/repos/RetoBancolombia/Reto/subscription",
                    "commits_url": "https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/RetoBancolombia/Reto/merges",
                    "archive_url": "https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/RetoBancolombia/Reto/downloads",
                    "issues_url": "https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}",
                    "releases_url": "https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/RetoBancolombia/Reto/deployments",
                    "created_at": 1713828633,
                    "updated_at": "2024-04-22T23:30:36Z",
                    "pushed_at": 1713851805,
                    "git_url": "git://github.com/RetoBancolombia/Reto.git",
                    "ssh_url": "git@github.com:RetoBancolombia/Reto.git",
                    "clone_url": "https://github.com/RetoBancolombia/Reto.git",
                    "svn_url": "https://github.com/RetoBancolombia/Reto",
                    "homepage": None,
                    "size": 54,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": None,
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": False,
                    "has_pages": False,
                    "has_discussions": False,
                    "forks_count": 0,
                    "mirror_url": None,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 0,
                    "license": None,
                    "allow_forking": False,
                    "is_template": False,
                    "web_commit_signoff_required": False,
                    "topics": [],
                    "visibility": "private",
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "main",
                    "stargazers": 0,
                    "master_branch": "main",
                    "organization": "RetoBancolombia",
                    "custom_properties": {}
                },
                "pusher": {
                    "name": "coldblade2000",
                    "email": "diegogranada7@gmail.com"
                },
                "organization": {
                    "login": "RetoBancolombia",
                    "id": 167820875,
                    "node_id": "O_kgDOCgC-Sw",
                    "url": "https://api.github.com/orgs/RetoBancolombia",
                    "repos_url": "https://api.github.com/orgs/RetoBancolombia/repos",
                    "events_url": "https://api.github.com/orgs/RetoBancolombia/events",
                    "hooks_url": "https://api.github.com/orgs/RetoBancolombia/hooks",
                    "issues_url": "https://api.github.com/orgs/RetoBancolombia/issues",
                    "members_url": "https://api.github.com/orgs/RetoBancolombia/members{/member}",
                    "public_members_url": "https://api.github.com/orgs/RetoBancolombia/public_members{/member}",
                    "avatar_url": "https://avatars.githubusercontent.com/u/167820875?v=4",
                    "description": None
                },
                "sender": {
                    "login": "coldblade2000",
                    "id": 1772063,
                    "node_id": "MDQ6VXNlcjE3NzIwNjM=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1772063?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/coldblade2000",
                    "html_url": "https://github.com/coldblade2000",
                    "followers_url": "https://api.github.com/users/coldblade2000/followers",
                    "following_url": "https://api.github.com/users/coldblade2000/following{/other_user}",
                    "gists_url": "https://api.github.com/users/coldblade2000/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/coldblade2000/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/coldblade2000/subscriptions",
                    "organizations_url": "https://api.github.com/users/coldblade2000/orgs",
                    "repos_url": "https://api.github.com/users/coldblade2000/repos",
                    "events_url": "https://api.github.com/users/coldblade2000/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/coldblade2000/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "created": False,
                "deleted": False,
                "forced": False,
                "base_ref": None,
                "compare": "https://github.com/RetoBancolombia/Reto/compare/0cc1a68aeeb0...40e200b00731",
                "commits": commits,
                "head_commit": commits[0]
            }
            ws_github.send(json.dumps(body))
            ws_github.close()
        elif type[0] == "pull_request.opened":
            print("Generating github pull_request.opened event")
            ws_github = create_connection(f"ws://{self.config["WS_HOST"]}/events/ingestion/github/ws",
                                          header={
                                              "Accept": "*/*",
                                              "Content-Type": "application/json",
                                              "User-Agent": "GitHub-Hookshot/300dae6",
                                              "X-GitHub-Delivery": str(uuid.uuid4()),
                                              "X-GitHub-Event": "pull_request",
                                              "X-GitHub-Hook-ID": "474170556",
                                              "X-GitHub-Hook-Installation-Target-ID": "167820875",
                                              "X-GitHub-Hook-Installation-Target-Type": "organization"
                                          })
            date_created = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(
                minutes=random.randint(0, 60 * 12),
                days=random.randint(0, 3 * 365)
            )
            body = {
                'action': 'opened',
                'number': 1,
                'pull_request': {
                    'url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1',
                    'id': 1835941657, 'node_id': 'PR_kwDOLx2EDc5tbj8Z',
                    'html_url': 'https://github.com/RetoBancolombia/Reto/pull/1',
                    'diff_url': 'https://github.com/RetoBancolombia/Reto/pull/1.diff',
                    'patch_url': 'https://github.com/RetoBancolombia/Reto/pull/1.patch',
                    'issue_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1',
                    'number': 1,
                    'state': 'closed',
                    'locked': False,
                    'title': fake.sentence(),
                    'user': {'login': 'coldblade2000', 'id': 1772063,
                             'node_id': 'MDQ6VXNlcjE3NzIwNjM=',
                             'avatar_url': 'https://avatars.githubusercontent.com/u/1772063?v=4',
                             'gravatar_id': '', 'url': 'https://api.github.com/users/coldblade2000',
                             'html_url': 'https://github.com/coldblade2000',
                             'followers_url': 'https://api.github.com/users/coldblade2000/followers',
                             'following_url': 'https://api.github.com/users/coldblade2000/following{/other_user}',
                             'gists_url': 'https://api.github.com/users/coldblade2000/gists{/gist_id}',
                             'starred_url': 'https://api.github.com/users/coldblade2000/starred{/owner}{/repo}',
                             'subscriptions_url': 'https://api.github.com/users/coldblade2000/subscriptions',
                             'organizations_url': 'https://api.github.com/users/coldblade2000/orgs',
                             'repos_url': 'https://api.github.com/users/coldblade2000/repos',
                             'events_url': 'https://api.github.com/users/coldblade2000/events{/privacy}',
                             'received_events_url': 'https://api.github.com/users/coldblade2000/received_events',
                             'type': 'User', 'site_admin': False}, 'body': None,
                    'created_at': date_created.isoformat(),
                    'updated_at': date_created.isoformat(),
                    'closed_at': None, 'merged_at': None, 'merge_commit_sha': None, 'assignee': None,
                    'assignees': [], 'requested_reviewers': [], 'requested_teams': [], 'labels': [],
                    'milestone': None, 'draft': False,
                    'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/commits',
                    'review_comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/comments',
                    'review_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/comments{/number}',
                    'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1/comments',
                    'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/40e200b007313b55c2d82fbf713a02d7be19a8d7',
                    'head': {'label': 'RetoBancolombia:develop', 'ref': 'develop',
                             'sha': '40e200b007313b55c2d82fbf713a02d7be19a8d7',
                             'user': {'login': 'RetoBancolombia', 'id': 167820875,
                                      'node_id': 'O_kgDOCgC-Sw',
                                      'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                      'gravatar_id': '',
                                      'url': 'https://api.github.com/users/RetoBancolombia',
                                      'html_url': 'https://github.com/RetoBancolombia',
                                      'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                      'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                      'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                      'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                      'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                      'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                      'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                      'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                      'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                      'type': 'Organization', 'site_admin': False},
                             'repo': {'id': 790463501, 'node_id': 'R_kgDOLx2EDQ', 'name': 'Reto',
                                      'full_name': 'RetoBancolombia/Reto', 'private': True,
                                      'owner': {'login': 'RetoBancolombia', 'id': 167820875,
                                                'node_id': 'O_kgDOCgC-Sw',
                                                'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                                'gravatar_id': '',
                                                'url': 'https://api.github.com/users/RetoBancolombia',
                                                'html_url': 'https://github.com/RetoBancolombia',
                                                'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                                'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                                'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                                'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                                'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                                'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                                'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                                'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                                'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                                'type': 'Organization', 'site_admin': False},
                                      'html_url': 'https://github.com/RetoBancolombia/Reto',
                                      'description': None, 'fork': False,
                                      'url': 'https://api.github.com/repos/RetoBancolombia/Reto',
                                      'forks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/forks',
                                      'keys_url': 'https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}',
                                      'collaborators_url': 'https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}',
                                      'teams_url': 'https://api.github.com/repos/RetoBancolombia/Reto/teams',
                                      'hooks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/hooks',
                                      'issue_events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}',
                                      'events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/events',
                                      'assignees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}',
                                      'branches_url': 'https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}',
                                      'tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/tags',
                                      'blobs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}',
                                      'git_tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}',
                                      'git_refs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}',
                                      'trees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}',
                                      'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}',
                                      'languages_url': 'https://api.github.com/repos/RetoBancolombia/Reto/languages',
                                      'stargazers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/stargazers',
                                      'contributors_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contributors',
                                      'subscribers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscribers',
                                      'subscription_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscription',
                                      'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}',
                                      'git_commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}',
                                      'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}',
                                      'issue_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}',
                                      'contents_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}',
                                      'compare_url': 'https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}',
                                      'merges_url': 'https://api.github.com/repos/RetoBancolombia/Reto/merges',
                                      'archive_url': 'https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}',
                                      'downloads_url': 'https://api.github.com/repos/RetoBancolombia/Reto/downloads',
                                      'issues_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}',
                                      'pulls_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}',
                                      'milestones_url': 'https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}',
                                      'notifications_url': 'https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}',
                                      'labels_url': 'https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}',
                                      'releases_url': 'https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}',
                                      'deployments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/deployments',
                                      'created_at': '2024-04-22T23:30:33Z',
                                      'updated_at': '2024-04-22T23:30:36Z',
                                      'pushed_at': '2024-04-23T06:08:43Z',
                                      'git_url': 'git://github.com/RetoBancolombia/Reto.git',
                                      'ssh_url': 'git@github.com:RetoBancolombia/Reto.git',
                                      'clone_url': 'https://github.com/RetoBancolombia/Reto.git',
                                      'svn_url': 'https://github.com/RetoBancolombia/Reto',
                                      'homepage': None, 'size': 57, 'stargazers_count': 0,
                                      'watchers_count': 0, 'language': None, 'has_issues': True,
                                      'has_projects': True, 'has_downloads': True, 'has_wiki': False,
                                      'has_pages': False, 'has_discussions': False, 'forks_count': 0,
                                      'mirror_url': None, 'archived': False, 'disabled': False,
                                      'open_issues_count': 1, 'license': None, 'allow_forking': False,
                                      'is_template': False, 'web_commit_signoff_required': False,
                                      'topics': [], 'visibility': 'private', 'forks': 0,
                                      'open_issues': 1, 'watchers': 0, 'default_branch': 'main',
                                      'allow_squash_merge': True, 'allow_merge_commit': True,
                                      'allow_rebase_merge': True, 'allow_auto_merge': False,
                                      'delete_branch_on_merge': False, 'allow_update_branch': False,
                                      'use_squash_pr_title_as_default': False,
                                      'squash_merge_commit_message': 'COMMIT_MESSAGES',
                                      'squash_merge_commit_title': 'COMMIT_OR_PR_TITLE',
                                      'merge_commit_message': 'PR_TITLE',
                                      'merge_commit_title': 'MERGE_MESSAGE'}},
                    'base': {'label': 'RetoBancolombia:main', 'ref': 'main',
                             'sha': '9b3ace861418a34babfbcf2c2d9a77f48b948172',
                             'user': {'login': 'RetoBancolombia', 'id': 167820875,
                                      'node_id': 'O_kgDOCgC-Sw',
                                      'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                      'gravatar_id': '',
                                      'url': 'https://api.github.com/users/RetoBancolombia',
                                      'html_url': 'https://github.com/RetoBancolombia',
                                      'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                      'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                      'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                      'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                      'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                      'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                      'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                      'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                      'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                      'type': 'Organization', 'site_admin': False},
                             'repo': {'id': 790463501, 'node_id': 'R_kgDOLx2EDQ', 'name': 'Reto',
                                      'full_name': 'RetoBancolombia/Reto', 'private': True,
                                      'owner': {'login': 'RetoBancolombia', 'id': 167820875,
                                                'node_id': 'O_kgDOCgC-Sw',
                                                'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                                'gravatar_id': '',
                                                'url': 'https://api.github.com/users/RetoBancolombia',
                                                'html_url': 'https://github.com/RetoBancolombia',
                                                'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                                'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                                'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                                'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                                'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                                'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                                'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                                'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                                'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                                'type': 'Organization', 'site_admin': False},
                                      'html_url': 'https://github.com/RetoBancolombia/Reto',
                                      'description': None, 'fork': False,
                                      'url': 'https://api.github.com/repos/RetoBancolombia/Reto',
                                      'forks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/forks',
                                      'keys_url': 'https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}',
                                      'collaborators_url': 'https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}',
                                      'teams_url': 'https://api.github.com/repos/RetoBancolombia/Reto/teams',
                                      'hooks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/hooks',
                                      'issue_events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}',
                                      'events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/events',
                                      'assignees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}',
                                      'branches_url': 'https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}',
                                      'tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/tags',
                                      'blobs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}',
                                      'git_tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}',
                                      'git_refs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}',
                                      'trees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}',
                                      'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}',
                                      'languages_url': 'https://api.github.com/repos/RetoBancolombia/Reto/languages',
                                      'stargazers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/stargazers',
                                      'contributors_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contributors',
                                      'subscribers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscribers',
                                      'subscription_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscription',
                                      'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}',
                                      'git_commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}',
                                      'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}',
                                      'issue_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}',
                                      'contents_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}',
                                      'compare_url': 'https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}',
                                      'merges_url': 'https://api.github.com/repos/RetoBancolombia/Reto/merges',
                                      'archive_url': 'https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}',
                                      'downloads_url': 'https://api.github.com/repos/RetoBancolombia/Reto/downloads',
                                      'issues_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}',
                                      'pulls_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}',
                                      'milestones_url': 'https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}',
                                      'notifications_url': 'https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}',
                                      'labels_url': 'https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}',
                                      'releases_url': 'https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}',
                                      'deployments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/deployments',
                                      'created_at': '2024-04-22T23:30:33Z',
                                      'updated_at': '2024-04-22T23:30:36Z',
                                      'pushed_at': '2024-04-23T06:08:43Z',
                                      'git_url': 'git://github.com/RetoBancolombia/Reto.git',
                                      'ssh_url': 'git@github.com:RetoBancolombia/Reto.git',
                                      'clone_url': 'https://github.com/RetoBancolombia/Reto.git',
                                      'svn_url': 'https://github.com/RetoBancolombia/Reto',
                                      'homepage': None, 'size': 57, 'stargazers_count': 0,
                                      'watchers_count': 0, 'language': None, 'has_issues': True,
                                      'has_projects': True, 'has_downloads': True, 'has_wiki': False,
                                      'has_pages': False, 'has_discussions': False, 'forks_count': 0,
                                      'mirror_url': None, 'archived': False, 'disabled': False,
                                      'open_issues_count': 1, 'license': None, 'allow_forking': False,
                                      'is_template': False, 'web_commit_signoff_required': False,
                                      'topics': [], 'visibility': 'private', 'forks': 0,
                                      'open_issues': 1, 'watchers': 0, 'default_branch': 'main',
                                      'allow_squash_merge': True, 'allow_merge_commit': True,
                                      'allow_rebase_merge': True, 'allow_auto_merge': False,
                                      'delete_branch_on_merge': False, 'allow_update_branch': False,
                                      'use_squash_pr_title_as_default': False,
                                      'squash_merge_commit_message': 'COMMIT_MESSAGES',
                                      'squash_merge_commit_title': 'COMMIT_OR_PR_TITLE',
                                      'merge_commit_message': 'PR_TITLE',
                                      'merge_commit_title': 'MERGE_MESSAGE'}}, '_links': {
                        'self': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1'},
                        'html': {'href': 'https://github.com/RetoBancolombia/Reto/pull/1'},
                        'issue': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1'},
                        'comments': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1/comments'},
                        'review_comments': {
                            'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/comments'},
                        'review_comment': {
                            'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/comments{/number}'},
                        'commits': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/commits'},
                        'statuses': {
                            'href': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/40e200b007313b55c2d82fbf713a02d7be19a8d7'}},
                    'author_association': 'CONTRIBUTOR', 'auto_merge': None,
                    'active_lock_reason': None, 'merged': False, 'mergeable': None, 'rebaseable': None,
                    'mergeable_state': 'unknown', 'merged_by': None, 'comments': 0,
                    'review_comments': 0, 'maintainer_can_modify': False, 'commits': 6,
                    'additions': 5056, 'deletions': 0, 'changed_files': 25
                },
                'repository': {
                    'id': 790463501, 'node_id': 'R_kgDOLx2EDQ', 'name': 'Reto',
                    'full_name': 'RetoBancolombia/Reto', 'private': True,
                    'owner': {
                        'login': 'RetoBancolombia', 'id': 167820875, 'node_id': 'O_kgDOCgC-Sw',
                        'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                        'gravatar_id': '', 'url': 'https://api.github.com/users/RetoBancolombia',
                        'html_url': 'https://github.com/RetoBancolombia',
                        'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                        'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                        'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                        'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                        'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                        'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                        'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                        'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                        'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                        'type': 'Organization', 'site_admin': False
                    },
                    'html_url': 'https://github.com/RetoBancolombia/Reto', 'description': None,
                    'fork': False, 'url': 'https://api.github.com/repos/RetoBancolombia/Reto',
                    'forks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/forks',
                    'keys_url': 'https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}',
                    'collaborators_url': 'https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}',
                    'teams_url': 'https://api.github.com/repos/RetoBancolombia/Reto/teams',
                    'hooks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/hooks',
                    'issue_events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}',
                    'events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/events',
                    'assignees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}',
                    'branches_url': 'https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}',
                    'tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/tags',
                    'blobs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}',
                    'git_tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}',
                    'git_refs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}',
                    'trees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}',
                    'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}',
                    'languages_url': 'https://api.github.com/repos/RetoBancolombia/Reto/languages',
                    'stargazers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/stargazers',
                    'contributors_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contributors',
                    'subscribers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscribers',
                    'subscription_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscription',
                    'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}',
                    'git_commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}',
                    'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}',
                    'issue_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}',
                    'contents_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}',
                    'compare_url': 'https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}',
                    'merges_url': 'https://api.github.com/repos/RetoBancolombia/Reto/merges',
                    'archive_url': 'https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}',
                    'downloads_url': 'https://api.github.com/repos/RetoBancolombia/Reto/downloads',
                    'issues_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}',
                    'pulls_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}',
                    'milestones_url': 'https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}',
                    'notifications_url': 'https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}',
                    'labels_url': 'https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}',
                    'releases_url': 'https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}',
                    'deployments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/deployments',
                    'created_at': '2024-04-22T23:30:33Z', 'updated_at': '2024-04-22T23:30:36Z',
                    'pushed_at': '2024-04-23T06:08:43Z',
                    'git_url': 'git://github.com/RetoBancolombia/Reto.git',
                    'ssh_url': 'git@github.com:RetoBancolombia/Reto.git',
                    'clone_url': 'https://github.com/RetoBancolombia/Reto.git',
                    'svn_url': 'https://github.com/RetoBancolombia/Reto', 'homepage': None, 'size': 57,
                    'stargazers_count': 0, 'watchers_count': 0, 'language': None, 'has_issues': True,
                    'has_projects': True, 'has_downloads': True, 'has_wiki': False, 'has_pages': False,
                    'has_discussions': False, 'forks_count': 0, 'mirror_url': None, 'archived': False,
                    'disabled': False, 'open_issues_count': 1, 'license': None, 'allow_forking': False,
                    'is_template': False, 'web_commit_signoff_required': False, 'topics': [],
                    'visibility': 'private', 'forks': 0, 'open_issues': 1, 'watchers': 0,
                    'default_branch': 'main', 'custom_properties': {}
                },
                'organization': {
                    'login': 'RetoBancolombia', 'id': 167820875, 'node_id': 'O_kgDOCgC-Sw',
                    'url': 'https://api.github.com/orgs/RetoBancolombia',
                    'repos_url': 'https://api.github.com/orgs/RetoBancolombia/repos',
                    'events_url': 'https://api.github.com/orgs/RetoBancolombia/events',
                    'hooks_url': 'https://api.github.com/orgs/RetoBancolombia/hooks',
                    'issues_url': 'https://api.github.com/orgs/RetoBancolombia/issues',
                    'members_url': 'https://api.github.com/orgs/RetoBancolombia/members{/member}',
                    'public_members_url': 'https://api.github.com/orgs/RetoBancolombia/public_members{/member}',
                    'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                    'description': None
                },
                'sender': {
                    'login': 'coldblade2000', 'id': 1772063, 'node_id': 'MDQ6VXNlcjE3NzIwNjM=',
                    'avatar_url': 'https://avatars.githubusercontent.com/u/1772063?v=4', 'gravatar_id': '',
                    'url': 'https://api.github.com/users/coldblade2000',
                    'html_url': 'https://github.com/coldblade2000',
                    'followers_url': 'https://api.github.com/users/coldblade2000/followers',
                    'following_url': 'https://api.github.com/users/coldblade2000/following{/other_user}',
                    'gists_url': 'https://api.github.com/users/coldblade2000/gists{/gist_id}',
                    'starred_url': 'https://api.github.com/users/coldblade2000/starred{/owner}{/repo}',
                    'subscriptions_url': 'https://api.github.com/users/coldblade2000/subscriptions',
                    'organizations_url': 'https://api.github.com/users/coldblade2000/orgs',
                    'repos_url': 'https://api.github.com/users/coldblade2000/repos',
                    'events_url': 'https://api.github.com/users/coldblade2000/events{/privacy}',
                    'received_events_url': 'https://api.github.com/users/coldblade2000/received_events',
                    'type': 'User', 'site_admin': False
                }
            }

            ws_github.send(json.dumps(body))
            ws_github.close()
        elif type[0] == "pull_request.closed":
            print("generating github pull_request.closed event")
            ws_github = create_connection(f"ws://{self.config["WS_HOST"]}/events/ingestion/github/ws",
                                          header={
                                              "Accept": "*/*",
                                              "Content-Type": "application/json",
                                              "User-Agent": "GitHub-Hookshot/300dae6",
                                              "X-GitHub-Delivery": str(uuid.uuid4()),
                                              "X-GitHub-Event": "pull_request",
                                              "X-GitHub-Hook-ID": "474170556",
                                              "X-GitHub-Hook-Installation-Target-ID": "167820875",
                                              "X-GitHub-Hook-Installation-Target-Type": "organization"
                                          })
            date_created = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(
                minutes=random.randint(0, 60 * 12),
                days=random.randint(0, 3 * 365))
            body = {
                'action': 'closed',
                'number': 1,
                'pull_request': {
                    'url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1',
                    'id': 1835941657, 'node_id': 'PR_kwDOLx2EDc5tbj8Z',
                    'html_url': 'https://github.com/RetoBancolombia/Reto/pull/1',
                    'diff_url': 'https://github.com/RetoBancolombia/Reto/pull/1.diff',
                    'patch_url': 'https://github.com/RetoBancolombia/Reto/pull/1.patch',
                    'issue_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1',
                    'number': 1,
                    'state': 'closed',
                    'locked': False,
                    'title': fake.sentence(),
                    'user': {'login': 'coldblade2000', 'id': 1772063,
                             'node_id': 'MDQ6VXNlcjE3NzIwNjM=',
                             'avatar_url': 'https://avatars.githubusercontent.com/u/1772063?v=4',
                             'gravatar_id': '', 'url': 'https://api.github.com/users/coldblade2000',
                             'html_url': 'https://github.com/coldblade2000',
                             'followers_url': 'https://api.github.com/users/coldblade2000/followers',
                             'following_url': 'https://api.github.com/users/coldblade2000/following{/other_user}',
                             'gists_url': 'https://api.github.com/users/coldblade2000/gists{/gist_id}',
                             'starred_url': 'https://api.github.com/users/coldblade2000/starred{/owner}{/repo}',
                             'subscriptions_url': 'https://api.github.com/users/coldblade2000/subscriptions',
                             'organizations_url': 'https://api.github.com/users/coldblade2000/orgs',
                             'repos_url': 'https://api.github.com/users/coldblade2000/repos',
                             'events_url': 'https://api.github.com/users/coldblade2000/events{/privacy}',
                             'received_events_url': 'https://api.github.com/users/coldblade2000/received_events',
                             'type': 'User', 'site_admin': False}, 'body': None,
                    'created_at': date_created.isoformat(),
                    'updated_at': (date_created + datetime.timedelta(hours=2)).isoformat(),
                    'closed_at': (date_created + datetime.timedelta(hours=2)).isoformat(),
                    'merged_at': (date_created + datetime.timedelta(hours=2)).isoformat(),
                    'merge_commit_sha': "0b4c974b0684191e76962f8d839c93473319a231", 'assignee': None,
                    'assignees': [], 'requested_reviewers': [], 'requested_teams': [], 'labels': [],
                    'milestone': None, 'draft': False,
                    'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/commits',
                    'review_comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/comments',
                    'review_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/comments{/number}',
                    'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1/comments',
                    'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/40e200b007313b55c2d82fbf713a02d7be19a8d7',
                    'head': {'label': 'RetoBancolombia:develop', 'ref': 'develop',
                             'sha': '40e200b007313b55c2d82fbf713a02d7be19a8d7',
                             'user': {'login': 'RetoBancolombia', 'id': 167820875,
                                      'node_id': 'O_kgDOCgC-Sw',
                                      'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                      'gravatar_id': '',
                                      'url': 'https://api.github.com/users/RetoBancolombia',
                                      'html_url': 'https://github.com/RetoBancolombia',
                                      'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                      'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                      'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                      'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                      'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                      'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                      'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                      'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                      'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                      'type': 'Organization', 'site_admin': False},
                             'repo': {'id': 790463501, 'node_id': 'R_kgDOLx2EDQ', 'name': 'Reto',
                                      'full_name': 'RetoBancolombia/Reto', 'private': True,
                                      'owner': {'login': 'RetoBancolombia', 'id': 167820875,
                                                'node_id': 'O_kgDOCgC-Sw',
                                                'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                                'gravatar_id': '',
                                                'url': 'https://api.github.com/users/RetoBancolombia',
                                                'html_url': 'https://github.com/RetoBancolombia',
                                                'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                                'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                                'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                                'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                                'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                                'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                                'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                                'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                                'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                                'type': 'Organization', 'site_admin': False},
                                      'html_url': 'https://github.com/RetoBancolombia/Reto',
                                      'description': None, 'fork': False,
                                      'url': 'https://api.github.com/repos/RetoBancolombia/Reto',
                                      'forks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/forks',
                                      'keys_url': 'https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}',
                                      'collaborators_url': 'https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}',
                                      'teams_url': 'https://api.github.com/repos/RetoBancolombia/Reto/teams',
                                      'hooks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/hooks',
                                      'issue_events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}',
                                      'events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/events',
                                      'assignees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}',
                                      'branches_url': 'https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}',
                                      'tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/tags',
                                      'blobs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}',
                                      'git_tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}',
                                      'git_refs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}',
                                      'trees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}',
                                      'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}',
                                      'languages_url': 'https://api.github.com/repos/RetoBancolombia/Reto/languages',
                                      'stargazers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/stargazers',
                                      'contributors_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contributors',
                                      'subscribers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscribers',
                                      'subscription_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscription',
                                      'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}',
                                      'git_commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}',
                                      'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}',
                                      'issue_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}',
                                      'contents_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}',
                                      'compare_url': 'https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}',
                                      'merges_url': 'https://api.github.com/repos/RetoBancolombia/Reto/merges',
                                      'archive_url': 'https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}',
                                      'downloads_url': 'https://api.github.com/repos/RetoBancolombia/Reto/downloads',
                                      'issues_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}',
                                      'pulls_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}',
                                      'milestones_url': 'https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}',
                                      'notifications_url': 'https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}',
                                      'labels_url': 'https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}',
                                      'releases_url': 'https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}',
                                      'deployments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/deployments',
                                      'created_at': '2024-04-22T23:30:33Z',
                                      'updated_at': '2024-04-22T23:30:36Z',
                                      'pushed_at': '2024-04-23T06:08:43Z',
                                      'git_url': 'git://github.com/RetoBancolombia/Reto.git',
                                      'ssh_url': 'git@github.com:RetoBancolombia/Reto.git',
                                      'clone_url': 'https://github.com/RetoBancolombia/Reto.git',
                                      'svn_url': 'https://github.com/RetoBancolombia/Reto',
                                      'homepage': None, 'size': 57, 'stargazers_count': 0,
                                      'watchers_count': 0, 'language': None, 'has_issues': True,
                                      'has_projects': True, 'has_downloads': True, 'has_wiki': False,
                                      'has_pages': False, 'has_discussions': False, 'forks_count': 0,
                                      'mirror_url': None, 'archived': False, 'disabled': False,
                                      'open_issues_count': 1, 'license': None, 'allow_forking': False,
                                      'is_template': False, 'web_commit_signoff_required': False,
                                      'topics': [], 'visibility': 'private', 'forks': 0,
                                      'open_issues': 1, 'watchers': 0, 'default_branch': 'main',
                                      'allow_squash_merge': True, 'allow_merge_commit': True,
                                      'allow_rebase_merge': True, 'allow_auto_merge': False,
                                      'delete_branch_on_merge': False, 'allow_update_branch': False,
                                      'use_squash_pr_title_as_default': False,
                                      'squash_merge_commit_message': 'COMMIT_MESSAGES',
                                      'squash_merge_commit_title': 'COMMIT_OR_PR_TITLE',
                                      'merge_commit_message': 'PR_TITLE',
                                      'merge_commit_title': 'MERGE_MESSAGE'}},
                    'base': {'label': 'RetoBancolombia:main', 'ref': 'main',
                             'sha': '9b3ace861418a34babfbcf2c2d9a77f48b948172',
                             'user': {'login': 'RetoBancolombia', 'id': 167820875,
                                      'node_id': 'O_kgDOCgC-Sw',
                                      'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                      'gravatar_id': '',
                                      'url': 'https://api.github.com/users/RetoBancolombia',
                                      'html_url': 'https://github.com/RetoBancolombia',
                                      'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                      'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                      'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                      'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                      'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                      'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                      'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                      'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                      'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                      'type': 'Organization', 'site_admin': False},
                             'repo': {'id': 790463501, 'node_id': 'R_kgDOLx2EDQ', 'name': 'Reto',
                                      'full_name': 'RetoBancolombia/Reto', 'private': True,
                                      'owner': {'login': 'RetoBancolombia', 'id': 167820875,
                                                'node_id': 'O_kgDOCgC-Sw',
                                                'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                                                'gravatar_id': '',
                                                'url': 'https://api.github.com/users/RetoBancolombia',
                                                'html_url': 'https://github.com/RetoBancolombia',
                                                'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                                                'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                                                'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                                                'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                                                'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                                                'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                                                'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                                                'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                                                'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                                                'type': 'Organization', 'site_admin': False},
                                      'html_url': 'https://github.com/RetoBancolombia/Reto',
                                      'description': None, 'fork': False,
                                      'url': 'https://api.github.com/repos/RetoBancolombia/Reto',
                                      'forks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/forks',
                                      'keys_url': 'https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}',
                                      'collaborators_url': 'https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}',
                                      'teams_url': 'https://api.github.com/repos/RetoBancolombia/Reto/teams',
                                      'hooks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/hooks',
                                      'issue_events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}',
                                      'events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/events',
                                      'assignees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}',
                                      'branches_url': 'https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}',
                                      'tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/tags',
                                      'blobs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}',
                                      'git_tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}',
                                      'git_refs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}',
                                      'trees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}',
                                      'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}',
                                      'languages_url': 'https://api.github.com/repos/RetoBancolombia/Reto/languages',
                                      'stargazers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/stargazers',
                                      'contributors_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contributors',
                                      'subscribers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscribers',
                                      'subscription_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscription',
                                      'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}',
                                      'git_commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}',
                                      'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}',
                                      'issue_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}',
                                      'contents_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}',
                                      'compare_url': 'https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}',
                                      'merges_url': 'https://api.github.com/repos/RetoBancolombia/Reto/merges',
                                      'archive_url': 'https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}',
                                      'downloads_url': 'https://api.github.com/repos/RetoBancolombia/Reto/downloads',
                                      'issues_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}',
                                      'pulls_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}',
                                      'milestones_url': 'https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}',
                                      'notifications_url': 'https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}',
                                      'labels_url': 'https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}',
                                      'releases_url': 'https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}',
                                      'deployments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/deployments',
                                      'created_at': '2024-04-22T23:30:33Z',
                                      'updated_at': '2024-04-22T23:30:36Z',
                                      'pushed_at': '2024-04-23T06:08:43Z',
                                      'git_url': 'git://github.com/RetoBancolombia/Reto.git',
                                      'ssh_url': 'git@github.com:RetoBancolombia/Reto.git',
                                      'clone_url': 'https://github.com/RetoBancolombia/Reto.git',
                                      'svn_url': 'https://github.com/RetoBancolombia/Reto',
                                      'homepage': None, 'size': 57, 'stargazers_count': 0,
                                      'watchers_count': 0, 'language': None, 'has_issues': True,
                                      'has_projects': True, 'has_downloads': True, 'has_wiki': False,
                                      'has_pages': False, 'has_discussions': False, 'forks_count': 0,
                                      'mirror_url': None, 'archived': False, 'disabled': False,
                                      'open_issues_count': 1, 'license': None, 'allow_forking': False,
                                      'is_template': False, 'web_commit_signoff_required': False,
                                      'topics': [], 'visibility': 'private', 'forks': 0,
                                      'open_issues': 1, 'watchers': 0, 'default_branch': 'main',
                                      'allow_squash_merge': True, 'allow_merge_commit': True,
                                      'allow_rebase_merge': True, 'allow_auto_merge': False,
                                      'delete_branch_on_merge': False, 'allow_update_branch': False,
                                      'use_squash_pr_title_as_default': False,
                                      'squash_merge_commit_message': 'COMMIT_MESSAGES',
                                      'squash_merge_commit_title': 'COMMIT_OR_PR_TITLE',
                                      'merge_commit_message': 'PR_TITLE',
                                      'merge_commit_title': 'MERGE_MESSAGE'}},
                    '_links': {
                        'self': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1'},
                        'html': {'href': 'https://github.com/RetoBancolombia/Reto/pull/1'},
                        'issue': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1'},
                        'comments': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/1/comments'},
                        'review_comments': {
                            'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/comments'},
                        'review_comment': {
                            'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/comments{/number}'},
                        'commits': {'href': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls/1/commits'},
                        'statuses': {
                            'href': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/40e200b007313b55c2d82fbf713a02d7be19a8d7'}},
                    'author_association': 'CONTRIBUTOR', 'auto_merge': None,
                    'active_lock_reason': None, 'merged': False, 'mergeable': None, 'rebaseable': None,
                    'mergeable_state': 'unknown', 'merged_by': None, 'comments': 0,
                    'review_comments': 0, 'maintainer_can_modify': False, 'commits': 6,
                    'additions': 5056, 'deletions': 0, 'changed_files': 25
                },
                'repository': {
                    'id': 790463501, 'node_id': 'R_kgDOLx2EDQ', 'name': 'Reto',
                    'full_name': 'RetoBancolombia/Reto', 'private': True,
                    'owner': {
                        'login': 'RetoBancolombia', 'id': 167820875, 'node_id': 'O_kgDOCgC-Sw',
                        'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                        'gravatar_id': '', 'url': 'https://api.github.com/users/RetoBancolombia',
                        'html_url': 'https://github.com/RetoBancolombia',
                        'followers_url': 'https://api.github.com/users/RetoBancolombia/followers',
                        'following_url': 'https://api.github.com/users/RetoBancolombia/following{/other_user}',
                        'gists_url': 'https://api.github.com/users/RetoBancolombia/gists{/gist_id}',
                        'starred_url': 'https://api.github.com/users/RetoBancolombia/starred{/owner}{/repo}',
                        'subscriptions_url': 'https://api.github.com/users/RetoBancolombia/subscriptions',
                        'organizations_url': 'https://api.github.com/users/RetoBancolombia/orgs',
                        'repos_url': 'https://api.github.com/users/RetoBancolombia/repos',
                        'events_url': 'https://api.github.com/users/RetoBancolombia/events{/privacy}',
                        'received_events_url': 'https://api.github.com/users/RetoBancolombia/received_events',
                        'type': 'Organization', 'site_admin': False
                    },
                    'html_url': 'https://github.com/RetoBancolombia/Reto', 'description': None,
                    'fork': False, 'url': 'https://api.github.com/repos/RetoBancolombia/Reto',
                    'forks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/forks',
                    'keys_url': 'https://api.github.com/repos/RetoBancolombia/Reto/keys{/key_id}',
                    'collaborators_url': 'https://api.github.com/repos/RetoBancolombia/Reto/collaborators{/collaborator}',
                    'teams_url': 'https://api.github.com/repos/RetoBancolombia/Reto/teams',
                    'hooks_url': 'https://api.github.com/repos/RetoBancolombia/Reto/hooks',
                    'issue_events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/events{/number}',
                    'events_url': 'https://api.github.com/repos/RetoBancolombia/Reto/events',
                    'assignees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/assignees{/user}',
                    'branches_url': 'https://api.github.com/repos/RetoBancolombia/Reto/branches{/branch}',
                    'tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/tags',
                    'blobs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/blobs{/sha}',
                    'git_tags_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/tags{/sha}',
                    'git_refs_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/refs{/sha}',
                    'trees_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/trees{/sha}',
                    'statuses_url': 'https://api.github.com/repos/RetoBancolombia/Reto/statuses/{sha}',
                    'languages_url': 'https://api.github.com/repos/RetoBancolombia/Reto/languages',
                    'stargazers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/stargazers',
                    'contributors_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contributors',
                    'subscribers_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscribers',
                    'subscription_url': 'https://api.github.com/repos/RetoBancolombia/Reto/subscription',
                    'commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/commits{/sha}',
                    'git_commits_url': 'https://api.github.com/repos/RetoBancolombia/Reto/git/commits{/sha}',
                    'comments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/comments{/number}',
                    'issue_comment_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues/comments{/number}',
                    'contents_url': 'https://api.github.com/repos/RetoBancolombia/Reto/contents/{+path}',
                    'compare_url': 'https://api.github.com/repos/RetoBancolombia/Reto/compare/{base}...{head}',
                    'merges_url': 'https://api.github.com/repos/RetoBancolombia/Reto/merges',
                    'archive_url': 'https://api.github.com/repos/RetoBancolombia/Reto/{archive_format}{/ref}',
                    'downloads_url': 'https://api.github.com/repos/RetoBancolombia/Reto/downloads',
                    'issues_url': 'https://api.github.com/repos/RetoBancolombia/Reto/issues{/number}',
                    'pulls_url': 'https://api.github.com/repos/RetoBancolombia/Reto/pulls{/number}',
                    'milestones_url': 'https://api.github.com/repos/RetoBancolombia/Reto/milestones{/number}',
                    'notifications_url': 'https://api.github.com/repos/RetoBancolombia/Reto/notifications{?since,all,participating}',
                    'labels_url': 'https://api.github.com/repos/RetoBancolombia/Reto/labels{/name}',
                    'releases_url': 'https://api.github.com/repos/RetoBancolombia/Reto/releases{/id}',
                    'deployments_url': 'https://api.github.com/repos/RetoBancolombia/Reto/deployments',
                    'created_at': '2024-04-22T23:30:33Z', 'updated_at': '2024-04-22T23:30:36Z',
                    'pushed_at': '2024-04-23T06:08:43Z',
                    'git_url': 'git://github.com/RetoBancolombia/Reto.git',
                    'ssh_url': 'git@github.com:RetoBancolombia/Reto.git',
                    'clone_url': 'https://github.com/RetoBancolombia/Reto.git',
                    'svn_url': 'https://github.com/RetoBancolombia/Reto', 'homepage': None, 'size': 57,
                    'stargazers_count': 0, 'watchers_count': 0, 'language': None, 'has_issues': True,
                    'has_projects': True, 'has_downloads': True, 'has_wiki': False, 'has_pages': False,
                    'has_discussions': False, 'forks_count': 0, 'mirror_url': None, 'archived': False,
                    'disabled': False, 'open_issues_count': 1, 'license': None, 'allow_forking': False,
                    'is_template': False, 'web_commit_signoff_required': False, 'topics': [],
                    'visibility': 'private', 'forks': 0, 'open_issues': 1, 'watchers': 0,
                    'default_branch': 'main', 'custom_properties': {}
                },
                'organization': {
                    'login': 'RetoBancolombia', 'id': 167820875, 'node_id': 'O_kgDOCgC-Sw',
                    'url': 'https://api.github.com/orgs/RetoBancolombia',
                    'repos_url': 'https://api.github.com/orgs/RetoBancolombia/repos',
                    'events_url': 'https://api.github.com/orgs/RetoBancolombia/events',
                    'hooks_url': 'https://api.github.com/orgs/RetoBancolombia/hooks',
                    'issues_url': 'https://api.github.com/orgs/RetoBancolombia/issues',
                    'members_url': 'https://api.github.com/orgs/RetoBancolombia/members{/member}',
                    'public_members_url': 'https://api.github.com/orgs/RetoBancolombia/public_members{/member}',
                    'avatar_url': 'https://avatars.githubusercontent.com/u/167820875?v=4',
                    'description': None
                },
                'sender': {
                    'login': 'coldblade2000', 'id': 1772063, 'node_id': 'MDQ6VXNlcjE3NzIwNjM=',
                    'avatar_url': 'https://avatars.githubusercontent.com/u/1772063?v=4', 'gravatar_id': '',
                    'url': 'https://api.github.com/users/coldblade2000',
                    'html_url': 'https://github.com/coldblade2000',
                    'followers_url': 'https://api.github.com/users/coldblade2000/followers',
                    'following_url': 'https://api.github.com/users/coldblade2000/following{/other_user}',
                    'gists_url': 'https://api.github.com/users/coldblade2000/gists{/gist_id}',
                    'starred_url': 'https://api.github.com/users/coldblade2000/starred{/owner}{/repo}',
                    'subscriptions_url': 'https://api.github.com/users/coldblade2000/subscriptions',
                    'organizations_url': 'https://api.github.com/users/coldblade2000/orgs',
                    'repos_url': 'https://api.github.com/users/coldblade2000/repos',
                    'events_url': 'https://api.github.com/users/coldblade2000/events{/privacy}',
                    'received_events_url': 'https://api.github.com/users/coldblade2000/received_events',
                    'type': 'User', 'site_admin': False
                }
            }

            ws_github.send(json.dumps(body))
            ws_github.close()


def generate_github_commit():
    return {
        "id": os.urandom(10).hex(),
        "tree_id": os.urandom(10).hex(),
        "distinct": True,
        "message": fake.sentence(),
        "timestamp": (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(
            minutes=random.randint(0, 60 * 12),
            days=random.randint(0, 3 * 365)
        )).isoformat(),
        "url": "https://github.com/RetoBancolombia/Reto/commit/40e200b007313b55c2d82fbf713a02d7be19a8d7",
        "author": {
            "name": "Diego Granada M",
            "email": "diegogranada7@gmail.com",
            "username": "coldblade2000"
        },
        "committer": {
            "name": "Diego Granada M",
            "email": "diegogranada7@gmail.com",
            "username": "coldblade2000"
        },
        "added": [
            "event-ingestion/.idea/.gitignore",
            "event-ingestion/.idea/event-ingestion.iml",
            "event-ingestion/.idea/inspectionProfiles/profiles_settings.xml",
            "event-ingestion/.idea/misc.xml",
            "event-ingestion/.idea/modules.xml",
            "event-ingestion/.idea/vcs.xml",
            "event-ingestion/main.py"
        ],
        "removed": [],
        "modified": []
    }
